### ISSUE TITLE
feature/question-wizard

### ISSUE THREAD

**Issue by zack-w** [opoll/create.openpoll.io#7]
This feature describes the question creation wizard for a poll. After a client enters the general poll information, they are asked to create the actual 'poll' or 'survey' itself which consists of a series of questions. This feature requires only basic 'poll' creation functionality.

- [ ] A poll should support between 1 and 30 questions
- [ ] Questions will be sequential, with no 'branching' or conditional logic
- [ ] The user should be able to easily rearrange questions
- [ ] The user should be able to easily switch between questions being edited
- [ ] Supports 'Select One' question type
- [ ] Supports 'Select All That Apply' question type
- [ ] Generates a compliant `schemas/0.1/poll/poll.json` `questionOptions` field

**Comment by zack-w** [comment]
sample size and geographic narrowing are covered in a branch i am working on. see the comments of this commit:

https://github.com/opoll/create.openpoll.io/commit/f6550d5351975daff59fa739f0a2dbc13c3837b3

**Comment by jonjamison3** [comment]
#11 up!

**Comment by zack-w** [comment]
core functionality developed in #11
